name: BaseSwiftUI # The name of the App
settings:
  base:
    CODE_SIGN_STYLE: Manual
configs:
  Dev Debug: debug
  Staging Debug: debug
  Production Debug: debug
  Dev Release: release
  Staging Release: release
  Production Release: release
configFiles:
  Dev Debug: BaseSwiftUI/Config/xcconfigs/dev.xcconfig
  Staging Debug: BaseSwiftUI/Config/xcconfigs/staging.xcconfig
  Production Debug: BaseSwiftUI/Config/xcconfigs/production.xcconfig
  Dev Release: BaseSwiftUI/Config/xcconfigs/dev.xcconfig
  Staging Release: BaseSwiftUI/Config/xcconfigs/staging.xcconfig
  Production Release: BaseSwiftUI/Config/xcconfigs/production.xcconfig
options: # Some general settings for the project
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  indentWidth: 4 # indent by 4 spaces
  tabWidth: 4 # a tab is 4 spaces
packages:
    Alamofire:
        url: https://github.com/Alamofire/Alamofire.git
        version: 5.9.1
    Kingfisher:
        url: https://github.com/onevcat/Kingfisher.git
        version: 7.11.0
    LinkNavigator:
        url: https://github.com/interactord/LinkNavigator.git
        version: 1.2.5
    Factory:
        url: https://github.com/hmlongco/Factory.git
        version: 2.3.2
    Rswift:
        url: https://github.com/mac-cain13/R.swift.git
        version: 7.5.0
    ValidatedPropertyKit:
        url: https://github.com/SvenTiigi/ValidatedPropertyKit.git
        version: 0.0.4
    Firebase:
        url: https://github.com/firebase/firebase-ios-sdk.git
        version: 10.23.1
    Defaults:
        url: https://github.com/sindresorhus/Defaults.git
        version: 8.2.0
    Then:
        url: https://github.com/devxoul/Then.git
        version: 3.0.0

targets: # The List of our targets
  BaseSwiftUI:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    devices: [iPhone]
    info:
      path: BaseSwiftUI/Info.plist
      properties:
        CFBundleName: $(APP_NAME)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        API_ENDPOINT: $(API_ENDPOINT)
        API_VERSION: $(API_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen:
            UIImageName: splash
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait]
        CFBundleURLTypes:
            - CFBundleURLSchemes:
                - "testlink"
    sources:
      #Sources
      - path: BaseSwiftUI
    scheme:
      testTargets:
        - BaseSwiftUITests
      gatherCoverageData: true
      configVariants:
        - Dev
        - Staging
        - Production
    settings:
      base:
       TARGETED_DEVICE_FAMILY: 1
       OTHER_SWIFT_FLAGS: $(inherited) $(SWIFT_FLAGS)
      configs:
        Dev Debug:
            CODE_SIGN_IDENTITY: iPhone Developer
            PROVISIONING_PROFILE_SPECIFIER: Development Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Dev Release:
            CODE_SIGN_IDENTITY: iPhone Distribution
            PROVISIONING_PROFILE_SPECIFIER: Distribution Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Staging Debug:
            CODE_SIGN_IDENTITY: iPhone Developer
            PROVISIONING_PROFILE_SPECIFIER: Development Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Staging Release:
            CODE_SIGN_IDENTITY: iPhone Distribution
            PROVISIONING_PROFILE_SPECIFIER: Distribution Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Production Debug:
            CODE_SIGN_IDENTITY: iPhone Developer
            PROVISIONING_PROFILE_SPECIFIER: Development Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
        Production Release:
            CODE_SIGN_IDENTITY: iPhone Distribution
            PROVISIONING_PROFILE_SPECIFIER: Distribution Provisioning
            MARKETING_VERSION: 1.0.0
            CURRENT_PROJECT_VERSION: 1
            VERSIONING_SYSTEM: Apple Generic
            PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
    preBuildScripts:
      - name: Swiftlint
        basedOnDependencyAnalysis: false
        script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
      - name: SwiftFormat
        basedOnDependencyAnalysis: false
        script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                    swiftformat .
                else
                    echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                fi
    dependencies:
       - package: Alamofire
       - package: Kingfisher
       - package: LinkNavigator
       - package: Factory
       - package: ValidatedPropertyKit
       - package: Rswift
         product: RswiftLibrary
       - package: Firebase
         product: FirebaseAuth
       - package: Defaults
       - package: Then
    buildToolPlugins:
       - plugin: RswiftGenerateInternalResources
         package: Rswift

  BaseSwiftUITests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: BaseSwiftUITests
    info:
      path: BaseSwiftUITests/Info.plist
    dependencies:
      - target: BaseSwiftUI
